// <auto-generated />
using System;
using LaserPointer.WebApi.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LaserPointer.WebApi.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10");

            modelBuilder.Entity("LaserPointer.WebApi.Domain.Entities.Hash", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("JobId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlainValue")
                        .HasColumnType("TEXT")
                        .HasMaxLength(255);

                    b.Property<byte[]>("Value")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("Hashes");
                });

            modelBuilder.Entity("LaserPointer.WebApi.Domain.Entities.HashAlgo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasAlternateKey("Type");

                    b.ToTable("HashAlgos");
                });

            modelBuilder.Entity("LaserPointer.WebApi.Domain.Entities.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("HashAlgoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HashAlgoId1")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HashAlgoId");

                    b.HasIndex("HashAlgoId1");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("LaserPointer.WebApi.Domain.Entities.Hash", b =>
                {
                    b.HasOne("LaserPointer.WebApi.Domain.Entities.Job", "Job")
                        .WithMany("HashesToCrack")
                        .HasForeignKey("JobId");
                });

            modelBuilder.Entity("LaserPointer.WebApi.Domain.Entities.Job", b =>
                {
                    b.HasOne("LaserPointer.WebApi.Domain.Entities.HashAlgo", null)
                        .WithMany("Jobs")
                        .HasForeignKey("HashAlgoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaserPointer.WebApi.Domain.Entities.HashAlgo", "HashAlgo")
                        .WithMany()
                        .HasForeignKey("HashAlgoId1");
                });
#pragma warning restore 612, 618
        }
    }
}
